### ISSUE TITLE
ClientLib support for RcOutput ?

### ISSUE THREAD

**Issue by danpe** [dronekit/dronekit-android#17]
Will the ClientLib support RcOutput ?

**Comment by ne0fhyk** [comment]
@danpe Yes, RC Output support is on the roadmap.

**Comment by ne0fhyk** [comment]
@danpe sorry for the delay. I'm in the process of drafting the interface for the rc output. Could you provide some examples on how you're planning to make use of it, so the interface can be made to be as intuitive as possible.

**Comment by alextel69** [comment]
@ne0fhyk I would use this feature for gimbal control + copters yaw control

**Comment by ne0fhyk** [comment]
Gimbal control is available through the [GimbalApi](http://android.dronekit.io/javadoc/com/o3dr/android/client/apis/GimbalApi.html)
Copter control is available through the [ControlApi](http://android.dronekit.io/javadoc/com/o3dr/android/client/apis/ControlApi.html).
