### ISSUE TITLE
Support new controller mode change interface

### ISSUE THREAD

**Issue by djmedina** [dronekit/dronekit-android#222]
## Interface
sololink_config --get-ui-mode
prints 1 or 2 to stdout, return code is 0
sololink_config --set-ui-mode 1
sets it to mode 1, prints 1 to stdout, and return code is 0
sololink_config --set-ui-mode 2
sets it to mode 2, prints 2 to stdout, and return code is 0
sololink_config --set-ui-mode blahblah
prints usage to stdout and return code is 1
Sample session at console:
root@3dr_controller:/usr/bin# sololink_config --get-ui-mode
1
root@3dr_controller:/usr/bin# echo $?
0
root@3dr_controller:/usr/bin# sololink_config --set-ui-mode 2
2
root@3dr_controller:/usr/bin# echo $?
0
root@3dr_controller:/usr/bin# sololink_config --set-ui-mode 1
1
root@3dr_controller:/usr/bin# echo $?
0
root@3dr_controller:/usr/bin# sololink_config --get-ui-mode 
1
root@3dr_controller:/usr/bin# sololink_config --set-ui-mode 2
2
root@3dr_controller:/usr/bin# sololink_config --get-ui-mode
2
root@3dr_controller:/usr/bin# sololink_config --set-ui-mode 3
sololink_config --set-ui-mode [1|2]
root@3dr_controller:/usr/bin# echo $?
1
root@3dr_controller:/usr/bin# sololink_config --get-ui-mode
2
root@3dr_controller:/usr/bin#

**Comment by ne0fhyk** [comment]
Fixed by pr #250
