### ISSUE TITLE
organization transfer

### ISSUE THREAD

**Issue by mrpollo** [dronekit/dronekit-android#225]
- [x] transfer from diydrones to dronekit organization
- [ ] update CI's to fetch from right repo
- [ ] update links on README.md
- [ ] update links on docs
- [ ] update links on http://dronekit.io

@ne0fhyk please feel free to add to this list if you think something's missing!

**Comment by ne0fhyk** [comment]
Thanks for opening the issue, although while still needed this is low priority since github will automatically redirect all the old references to the new one.

**Comment by mrpollo** [comment]
yeah its just so we don't forget, maybe someone wants to contribute and doesn't know where, this is a good place to start !

**Comment by ne0fhyk** [comment]
Good idea!

On Thu, Jul 30, 2015, 10:42 AM Ramon Roche <notifications@github.com> wrote:

> yeah its just so we don't forget, maybe someone wants to contribute and
> doesn't know where, this is a good place to start !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dronekit/DroneKit-Android/issues/225#issuecomment-126414130>
> .
>
-- 
Fredia Huya-Kouadio
https://github.com/ne0fhyk
