### ISSUE TITLE
Incosistency with Maven

### ISSUE THREAD

**Issue by alextel69** [dronekit/dronekit-android#233]
Drone.changeVehicleMode is deprecated. Instead, VehicleApi should be used. 
But there is no VehicleApi class in library. 
I am using Android-DroneKit version 2.3.+

**Comment by ne0fhyk** [comment]
Are you seeing the deprecation warnings in the 2.3.+ library?
The VehicleApi is within the upcoming library update (v2.5.+), but you
should not be seeing deprecation warnings within the currently available
client library.

--
Fredia Huya-Kouadio
Android Tech Lead, 3D Robotics
fredia@3dr.com

**Comment by alextel69** [comment]
I switched to 2.3.34 (latest version on jcenter) and still face deprecations alongside with miss of reccomended classes

**Comment by ne0fhyk** [comment]
@alextel69 the issue should be fixed now since `dronekit-android v2.5.+` is now out and available.
