### ISSUE TITLE
Trigger tlog logging on arm/disarm events

### ISSUE THREAD

**Issue by ne0fhyk** [dronekit/dronekit-android#26]
Tlog is currently logged as soon as the app is connected to the vehicle.
Change it to start logging when the copter is armed, and stop when the copter is disarmed.

**Comment by Craig3DRobotics** [comment]
If the tlog does not start at the beginning of the power cycle to the vehicle then we need to have the parameters, waypoints, rally points, text messages, pre-arm checks that are sent prior to arming be written to the tlog file when it is created.  The tlog needs to have the time that the vehicle was powered up and the time that it was armed.
It would be very useful to have the option of still logging all data for some additional troubleshooting
