### ISSUE TITLE
Enable SIMPLE flight mode

### ISSUE THREAD

**Issue by dgmccut** [dronekit/dronekit-android#295]
The SIMPLE flight mode should be able to be entered by calling:

VehicleApi.getApi(drone).setVehicleMode(VehicleMode.COPTER_SIMPLE, this);

Here's the reference to SIMPLE mode
http://copter.ardupilot.com/wiki/simpleandsuper-simple-modes/#simple_mode

**Comment by squilter** [comment]
Simple mode isn't actually a `mode` like stabilize or loiter.  It is a flag that can be on or off for the real `mode`s.  So Loiter/stabilize/althold/etc can be flown with normal, simple, or super-simple.  So I don't think it is appropriate to call it with `setVehicleMode();`.

**Comment by dgmccut** [comment]
I agree. I'm new to all this.

**Comment by ne0fhyk** [comment]
Enabling `simple` flight mode is not yet supported via mavlink. Closing this for now.
