### ISSUE TITLE
Add `Reset ROI` mission item command

### ISSUE THREAD

**Issue by ne0fhyk** [dronekit/dronekit-android#312]

**Comment by ne0fhyk** [comment]
Fixed by PR #315

**Comment by billfor** [comment]
This breaks the latest tower app. Tower doesn't expect it and if a mission is downloaded that contains an old style ROI reset (lat,long,alt=0,0,0) then the entire mission is shown empty.

**Comment by ne0fhyk** [comment]
@billfor This have been fixed in version `3.2.1` which is currently undergoing beta testing. 
A fix will be pushed to 3DR Services as well for current and older versions of Tower.
