### ISSUE TITLE
Battery Status is not being displayed

### ISSUE THREAD

**Issue by Thoin** [dronekit/dronekit-android#313]
*Phone*: Samsung Galaxy S5
*3DR Services*: 1.4.3 beta 2
*Tower*: 3.2.0

@ne0fhyk, I can now successfully connect to my Pixhawk running PX4 firmware with the beta of 3DR services. It's great!

I get telemetry data in real time as expected. I do **NOT** get battery status though. Voltage and Current read 0.00, and R reads 0% and D has no data either. This is data that I get when using QGroundControl so I know my hardware is not at fault.

[3DR Service Logs](https://drive.google.com/folderview?id=0B-4Pt7stMkc8UzhzOE5uMGFqaGc&usp=sharing)

*I have not yet had the time to take my quadcopter out for a flight since this 3DR Services update, this was done without props, indoors. I will be taking it out this week and reporting any issues that arise.*

**Comment by ne0fhyk** [comment]
Fixed by pr #314

**Comment by ne0fhyk** [comment]
@Thoin I'll provide you with a build for testing.
