### ISSUE TITLE
Manual Control didn't work in guided mode

### ISSUE THREAD

**Issue by buqing2009** [dronekit/dronekit-android#366]
I want use virtual joystick to control copter using dronekit. But when i used the method **manualControl** in ControlApi, i debug the code, and already send the pitch, roll, throttle, but it didn't changed in SITL. 
Here is my code:
```java
 this.guide.manualControl((float) pitch_val, (float) roll_val, (float) throttle_val, new AbstractCommandListener() {
                    @Override
                    public void onSuccess() {
                        Log.e("bluking", "Controller successfully");
                    }

                    @Override
                    public void onError(int executionError) {

                    }

                    @Override
                    public void onTimeout() {

                    }
                });

```
It had been in Guided mode when using this method.
Can anyone help me fix this?

**Comment by ne0fhyk** [comment]
@buqing2009 closing this since the issue was due to the arducopter version you were running.
