### ISSUE TITLE
S100 and S110/S120 sensors size different

### ISSUE THREAD

**Issue by kikislater** [dronekit/dronekit-android#382]
Hi,

I saw the S100 and S110/S120 does not share the same sensor size in CameraInfo whereas it is the same sensor. The correct one is the S100

    <Name>Canon S100</Name>
    <SensorWidth>7.44</SensorWidth>
    <SensorHeight>5.58</SensorHeight>

    <Name>Canon S110/S120</Name>
    <SensorWidth>7.60</SensorWidth>
    <SensorHeight>5.70</SensorHeight>

Sincerely,

Sylvain

**Comment by ne0fhyk** [comment]
@kikislater Thanks for the update!
