### ISSUE TITLE
drone state not connected on LinkConnectionStatus.CONNECTED

### ISSUE THREAD

**Issue by MarthzElena** [dronekit/dronekit-android#383]
Hi,
I'm using dronekit-android:2.8.+, I'm adding a LinkListener to the connection parameters on the drone.connect() method. The thing is that even for the LinkConnectionStatus.CONNECTED case I'm getting drone.isConnected() = false.
I also tried with the State object and got the same results, is there another way to know if drone actually connect? Does this mean the drone is never connected?

**Comment by ne0fhyk** [comment]
@MarthzElena The `LinkConnectionStatus` only reports information about the link connection state. For example, the mobile device can be connected to the drone via `usb`, `tcp`, `udp`, `bluetooth`, etc, and the `LinkConnectionStatus` reports the state of that connection.
As such the `LinkConnectionStatus.CONNECTED` event doesn't imply there's a drone at the other end of the medium/link, it just mean that the link was established and is ready to be used.

To detect if the drone is connected, you can use the `drone.isConnected()` method which is also a wrapper to the `State.isConnected()` method. You can also register a [`DroneListener`](https://github.com/dronekit/dronekit-android/blob/4f965d97a3dad087390a947d0669683f1895949a/ClientLib/src/main/java/com/o3dr/android/client/interfaces/DroneListener.java) listener, and listens for the [`AttributeEvent.STATE_CONNECTED`](https://github.com/dronekit/dronekit-android/blob/4f965d97a3dad087390a947d0669683f1895949a/ClientLib/src/main/java/com/o3dr/services/android/lib/drone/attribute/AttributeEvent.java#L146) event through the `DroneListener#onDroneEvent(...)` method.
