### ISSUE TITLE
destinationDir (new File("${rootDir}/../dronekit-android-dev/ClientLib/libs")) should be destinationDir (new File("${rootDir}/../dronekit-android/ClientLib/libs"))

### ISSUE THREAD

**Issue by gumingpo** [dronekit/dronekit-android#400]
Considering Tower will remote-depend via compile 'com.o3dr.android:dronekit-android:2.8.0'.
The dronekit-android.2.8.0.aar should best contain Mavlink.jar via changing the dronekit-android/dependencyLibs/Mavlink/build.gradle from
destinationDir (new File("${rootDir}/../dronekit-android-dev/ClientLib/libs")) to destinationDir (new File("${rootDir}/../dronekit-android/ClientLib/libs"))

**Comment by chaviw** [comment]
This was fixed on branch `release-1.5.3`. This will be merged into develop soon
