### ISSUE TITLE
Make FollowApi accept locations supplied by the client

### ISSUE THREAD

**Issue by kellyschrock** [dronekit/dronekit-android#408]
FollowApi is limited in the ways it can be used, since it insists on only using the location of the device running the client application. It should be able to also accept an externally-supplied location from the application, so there are more options on what can be followed.

**Comment by ne0fhyk** [comment]
@kellyschrock sounds like a good idea. 
What do you think about the following changes to the `FollowApi` to provide that functionality:
* Add an overloaded method for `FollowApi#enableFollowMe(...)` with an additional (to be defined) `enum` parameter to specify the origin of the location updates
* Add `FollowApi#updateFollowLocation(android.location.Location location, ...)` to provide location updates.
* Update the `FollowApi#updateFollowParams(...)` method to allow switching between different location provider (i.e: device, custom).

**Comment by kellyschrock** [comment]
@ne0fhyk That sounds good. I have a branch _almost_ ready for PR that does a lot of this, but I'm currently using a boolean to indicate whether follow should be "external" or not. I like the enum idea more, actually. I can push it if you like and you can take a look.

**Comment by ne0fhyk** [comment]
@kellyschrock sounds good. looking forward to the PR!

**Comment by kellyschrock** [comment]
Here you go! :-) https://github.com/dronekit/dronekit-android/pull/410

Thanks,
Kelly
