### ISSUE TITLE
Mavlink error on Build

### ISSUE THREAD

**Issue by Gamma-Software** [dronekit/dronekit-android#413]
Hi guys ;)
I'm having a build issue when I want to build the dronekit library. The Gradle Build generate an error telling that the package of MAVLink doesn't exist. Here is the log:

![capture](https://cloud.githubusercontent.com/assets/6960910/16494811/0b824994-3eeb-11e6-8133-80447ffb94ca.PNG)

Everything is related to the MAVLink Lib.

Do you guys know what's going on ?
Thanks for the help ;)

**Comment by Gamma-Software** [comment]
No suggestion ?

**Comment by Gamma-Software** [comment]
Well, I finally solved the issue. We just have to use a different version name :/

**Comment by NbagusW** [comment]
Hi @Gamma-Software , how can u solve it? i had the sam probmels  wih u, but i still didnt know howto fix it.. ty

**Comment by Gamma-Software** [comment]
Make sure that the version of the Library is not conflicting with the current version of the release library (in the ClientLib Build.gradle). 
So change the version:
![capture](https://cloud.githubusercontent.com/assets/6960910/17101012/54630140-5272-11e6-8672-195a4860b262.PNG)

**Comment by NbagusW** [comment]
@Gamma-Software thanks but, i still have an error :( ,where should i change the version, or to know if its already have same version. 
PS: really sorry , im a newbie at this.

**Comment by Gamma-Software** [comment]
I think that the first version is 
VERSION_MAJOR = 2
VERSION_MINOR = 9
VERSION_PATCH = 0
VERSION_SUFFIX = "release"

You just have to change the version number (for instance: 
VERSION_PATCH = 1).

Otherwise, give me your message error

**Comment by ne0fhyk** [comment]
@NbagusW can you post your question on the [dronekit-android gitter channel](https://gitter.im/dronekit/dronekit-android) instead.

Thanks.
