### ISSUE TITLE
Remove default "3DR Services missing" dialog

### ISSUE THREAD

**Issue by alextel69** [dronekit/dronekit-android#429]
As I see it, most preferably for developer is to handle it on its own with custom style and text.

**Comment by ne0fhyk** [comment]
3DR services is being deprecated for the next release of the client library.

**Comment by alextel69** [comment]
Thank you for reply!

What will be instead of it?

And how client library miss will be handled there?

19 авг. 2016 г. 9:17 PM пользователь "Fredia Huya-Kouadio" <
notifications@github.com> написал:

**Comment by ne0fhyk** [comment]
@alextel69 all the logic will be in the client library, so there won't be an issue with mismatched components.
