### ISSUE TITLE
Allow option to change path where TLOG files are stored

### ISSUE THREAD

**Issue by idleup** [dronekit/dronekit-android#58]
On my Galaxy tablet they are currently stored in <tablet local drive>\Android\data\org.droidplanner.services.android\files\tlogs\org.droidplanner.android\ it would be nice to change that so they are written to my SD Card instead.

**Comment by Thalek** [comment]
That feature would be very useful for phones, as well.  My phone may not have enough device storage space left to install Android 5.x when it becomes available, while my SD storage space is almost untouched.

**Comment by ne0fhyk** [comment]
Solved in `version 3.0` branch
