### ISSUE TITLE
Unclear disconnect flow

### ISSUE THREAD

**Issue by alextel69** [dronekit/dronekit-android#94]
Per guide, one needs to listen to onStart/onStop events and disconnect during onStop. However, when configuration changes, onStop is called, so that drone is disconnected, while app still requires connection to drone. From user perspective it could be loss of drone control from, say, orientation change.
Reconnecting is not good idea, because drone could be in-flight, and sudden disconnect might cause a failsafe.

**Comment by alextel69** [comment]
@ne0fhyk any possible solution/approach?

**Comment by ne0fhyk** [comment]
@alextel69 this is more of an Android lifecycle issue. The solution in that case is to keep the drone connection state/logic in an Android component that's not subject to the Activity lifecycle. This can be a [Service](https://developer.android.com/reference/android/app/Service.html), or an [Application](https://developer.android.com/reference/android/app/Application.html) component.
